import React, { useState, useRef, useEffect, useMemo } from 'react';
import { Send, Trash2, Image as ImageIcon, Volume2 } from 'lucide-react';
import { BotConfig, ChatMessage } from '../types';
import { testBotResponse } from '../services/geminiService';

interface PlaygroundProps {
  config: BotConfig;
  isVisible: boolean;
}

const AVAILABLE_COMMANDS = [
  { cmd: '!pesquisa', desc: 'Busca na web (Google)' },
  { cmd: '!imaginar', desc: 'Gerar imagem (Gemini 2.5 Image)' },
  { cmd: '!falar', desc: 'Gerar áudio (Gemini 2.5 TTS)' },
  { cmd: '!wiki', desc: 'Resumo estilo Wikipédia' },
  { cmd: '!clima', desc: 'Previsão do tempo' },
  { cmd: '!historia', desc: 'Criar história criativa' },
  { cmd: '!traduzir', desc: 'Traduzir para PT-BR' },
  { cmd: '!bot', desc: 'Chat direto (sem search)' },
  { cmd: '!limpar', desc: 'Limpar terminal' },
  { cmd: '!config', desc: 'Ver configs atuais' },
  { cmd: '!status', desc: 'Checar saúde do sistema' },
];

const MessageItem = React.memo(({ msg }: { msg: ChatMessage }) => (
  <div className={`flex flex-col group ${msg.isBot ? 'items-start' : 'items-end'}`}>
    <div className="flex items-baseline gap-2 mb-1 opacity-50 text-[10px]">
      <span className={msg.isBot ? "text-charm-pink" : "text-charm-cyan"}>{msg.user}</span>
      <span>{msg.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })}</span>
    </div>
    
    <div className={`
      max-w-[85%] border-l-2 pl-3 py-1 flex flex-col gap-2
      ${msg.isBot 
        ? 'border-charm-pink text-charm-text' 
        : 'border-charm-cyan text-charm-text text-right'}
    `}>
      {msg.text && <p className="whitespace-pre-wrap leading-relaxed">{msg.text}</p>}
      
      {msg.image && (
        <div className="mt-2 rounded-lg overflow-hidden border border-charm-border shadow-lg max-w-sm">
           <img 
             src={msg.image} 
             alt="Generated by Gemini" 
             className="w-full h-auto object-cover hover:scale-105 transition-transform duration-500"
             loading="lazy"
           />
           <div className="bg-charm-card px-2 py-1 text-[10px] text-charm-subtext flex items-center gap-1 border-t border-charm-border">
              <ImageIcon className="w-3 h-3" />
              <span>gemini-2.5-flash-image</span>
           </div>
        </div>
      )}

      {msg.audio && (
        <div className="mt-2 bg-charm-card border border-charm-border rounded p-2 flex items-center gap-2 max-w-sm">
           <div className="bg-charm-purple/10 p-2 rounded-full text-charm-purple animate-pulse">
              <Volume2 className="w-4 h-4" />
           </div>
           <audio controls src={msg.audio} className="h-8 w-48 lg:w-64 custom-audio" />
           <span className="text-[10px] text-charm-subtext font-mono">24kHz</span>
        </div>
      )}
    </div>
  </div>
));

const Playground: React.FC<PlaygroundProps> = ({ config, isVisible }) => {
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: '1',
      user: 'Sistema',
      text: 'Ambiente Gemini 3 Flash inicializado. Pronto para o chat (Modo PT-BR + Grounding)...',
      timestamp: new Date(),
      isBot: true,
    }
  ]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  
  // Auto-complete State
  const [suggestions, setSuggestions] = useState(AVAILABLE_COMMANDS);
  const [showSuggestions, setShowSuggestions] = useState(false);
  const [activeSuggestionIndex, setActiveSuggestionIndex] = useState(0);

  // History State
  const [history, setHistory] = useState<string[]>([]);
  const [historyIndex, setHistoryIndex] = useState(-1);

  const messagesEndRef = useRef<HTMLDivElement>(null);
  const textAreaRef = useRef<HTMLTextAreaElement>(null);

  const scrollToBottom = () => {
    if (isVisible) {
      messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
    }
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, isVisible]);

  const handleInputChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const value = e.target.value;
    setInput(value);

    // Auto-complete logic
    if (value.startsWith('!')) {
      const searchTerm = value.toLowerCase();
      if (value.includes(' ')) {
        setShowSuggestions(false);
        return;
      }

      const filtered = AVAILABLE_COMMANDS.filter(c => 
        c.cmd.toLowerCase().startsWith(searchTerm)
      );

      if (filtered.length > 0) {
        setSuggestions(filtered);
        setShowSuggestions(true);
        setActiveSuggestionIndex(0);
      } else {
        setShowSuggestions(false);
      }
    } else {
      setShowSuggestions(false);
    }
  };

  const selectSuggestion = (cmd: string) => {
    setInput(cmd + ' ');
    setShowSuggestions(false);
    textAreaRef.current?.focus();
  };

  const handleSend = async () => {
    if (!input.trim() || loading) return;

    // Add to history
    setHistory(prev => [...prev, input]);
    setHistoryIndex(-1); // Reset history pointer

    // Client-side Command Interception
    const command = input.trim().split(' ')[0].toLowerCase();

    if (command === '!limpar') {
        setMessages([{
            id: Date.now().toString(),
            user: 'Sistema',
            text: 'Terminal limpo via comando.',
            timestamp: new Date(),
            isBot: true,
        }]);
        setInput('');
        return;
    }

    if (command === '!config') {
        const configMsg: ChatMessage = {
            id: Date.now().toString(),
            user: 'Sistema',
            text: `CONFIGURAÇÃO ATUAL:\n\nSystem Prompt: ${config.systemPrompt.substring(0, 50)}...\nTemp: ${config.temperature}\nThinking: ${config.thinkingLevel}\nEnabled: ${config.isEnabled}`,
            timestamp: new Date(),
            isBot: true,
        };
        setMessages(prev => [...prev, { id: Date.now().toString(), user: 'VOCÊ', text: input, timestamp: new Date(), isBot: false }, configMsg]);
        setInput('');
        return;
    }

    if (command === '!status') {
         const statusMsg: ChatMessage = {
            id: Date.now().toString(),
            user: 'Sistema',
            text: `STATUS DO SISTEMA:\n\n[OK] API Gateway\n[OK] Gemini 3 Flash\n[OK] Twitch Connection\nLatency: ~45ms`,
            timestamp: new Date(),
            isBot: true,
        };
        setMessages(prev => [...prev, { id: Date.now().toString(), user: 'VOCÊ', text: input, timestamp: new Date(), isBot: false }, statusMsg]);
        setInput('');
        return;
    }

    // Normal AI Flow
    const userMsg: ChatMessage = {
      id: Date.now().toString(),
      user: 'VOCÊ',
      text: input,
      timestamp: new Date(),
      isBot: false,
    };

    setMessages(prev => [...prev, userMsg]);
    setInput('');
    setLoading(true);

    // Call Gemini Service
    const response = await testBotResponse(input, config);

    const botMsg: ChatMessage = {
      id: (Date.now() + 1).toString(),
      user: 'BOT',
      text: response.text,
      image: response.image,
      audio: response.audio,
      timestamp: new Date(),
      isBot: true,
    };

    setMessages(prev => [...prev, botMsg]);
    setLoading(false);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    // 1. Handle Auto-complete navigation (Priority)
    if (showSuggestions) {
      if (e.key === 'ArrowUp') {
        e.preventDefault();
        setActiveSuggestionIndex(prev => (prev > 0 ? prev - 1 : suggestions.length - 1));
        return;
      }
      if (e.key === 'ArrowDown') {
        e.preventDefault();
        setActiveSuggestionIndex(prev => (prev < suggestions.length - 1 ? prev + 1 : 0));
        return;
      }
      if (e.key === 'Tab' || e.key === 'Enter') {
        e.preventDefault();
        if (suggestions[activeSuggestionIndex]) {
          selectSuggestion(suggestions[activeSuggestionIndex].cmd);
        }
        return;
      }
      if (e.key === 'Escape') {
        e.preventDefault();
        setShowSuggestions(false);
        return;
      }
    }

    // 2. Handle History Navigation (When suggestions are closed)
    if (!showSuggestions) {
      if (e.key === 'ArrowUp') {
        e.preventDefault();
        if (history.length > 0) {
          const newIndex = historyIndex === -1 ? history.length - 1 : Math.max(0, historyIndex - 1);
          setHistoryIndex(newIndex);
          setInput(history[newIndex]);
          // Move cursor to end
          setTimeout(() => {
             if(textAreaRef.current) {
                textAreaRef.current.selectionStart = textAreaRef.current.value.length;
                textAreaRef.current.selectionEnd = textAreaRef.current.value.length;
             }
          }, 0);
        }
        return;
      }
      if (e.key === 'ArrowDown') {
        e.preventDefault();
        if (historyIndex !== -1) {
          const newIndex = historyIndex + 1;
          if (newIndex >= history.length) {
             setHistoryIndex(-1);
             setInput('');
          } else {
             setHistoryIndex(newIndex);
             setInput(history[newIndex]);
          }
        }
        return;
      }
    }

    // 3. Handle Send
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  return (
    <div className="h-[calc(100vh-8rem)] flex flex-col lg:flex-row gap-6">
      
      {/* Chat Area */}
      <div className="flex-1 flex flex-col bg-charm-bg border border-charm-border rounded-lg overflow-hidden shadow-2xl relative">
         <div className="absolute top-0 inset-x-0 h-1 bg-gradient-to-r from-charm-pink via-charm-purple to-charm-cyan"></div>
        
        {/* Chat Header */}
        <div className="p-3 border-b border-charm-border bg-charm-card flex justify-between items-center">
          <div className="flex items-center gap-3">
             <div className="text-charm-purple">
                ⬢
             </div>
             <div>
                <h3 className="font-bold text-charm-text text-sm tracking-wide">TEST_ENV <span className="text-charm-subtext font-normal">// gemini-3-flash</span></h3>
             </div>
          </div>
          <button 
            onClick={() => setMessages([])}
            className="p-2 hover:text-charm-red transition-colors text-charm-subtext"
            title="Limpar Buffer"
          >
            <Trash2 className="w-4 h-4" />
          </button>
        </div>

        {/* Messages List - Terminal Style */}
        <div className="flex-1 overflow-y-auto p-4 space-y-4 font-mono text-sm bg-[#101014]">
          {messages.map((msg) => (
            <MessageItem key={msg.id} msg={msg} />
          ))}
          {loading && (
             <div className="flex flex-col items-start animate-pulse">
               <div className="flex items-baseline gap-2 mb-1 opacity-50 text-[10px]">
                 <span className="text-charm-pink">BOT</span>
                 <span>Processando...</span>
               </div>
               <div className="border-l-2 border-charm-pink pl-3 py-1 text-charm-pink">
                  █
               </div>
             </div>
          )}
          <div ref={messagesEndRef} />
        </div>

        {/* Input Area */}
        <div className="p-4 bg-charm-card border-t border-charm-border relative">
          
          {/* Suggestions Popup */}
          {showSuggestions && (
            <div className="absolute bottom-full left-4 mb-2 w-72 bg-charm-bg border border-charm-border rounded-lg shadow-2xl overflow-hidden z-20 animate-fade-in">
               <div className="bg-charm-card px-3 py-1 border-b border-charm-border text-[10px] text-charm-subtext uppercase tracking-wider font-bold">
                  Comandos Sugeridos
               </div>
               {suggestions.map((s, idx) => (
                 <button
                   key={s.cmd}
                   className={`w-full text-left px-3 py-2 text-xs font-mono flex justify-between items-center transition-colors
                     ${idx === activeSuggestionIndex 
                        ? 'bg-charm-purple/10 text-charm-cyan border-l-2 border-charm-cyan' 
                        : 'text-charm-subtext hover:bg-charm-hover border-l-2 border-transparent'}`}
                   onClick={() => selectSuggestion(s.cmd)}
                   onMouseEnter={() => setActiveSuggestionIndex(idx)}
                 >
                    <span className="font-bold">{s.cmd}</span>
                    <span className="opacity-50 text-[10px] truncate ml-2">{s.desc}</span>
                 </button>
               ))}
            </div>
          )}

          <div className="flex items-center gap-2 bg-charm-bg border border-charm-border rounded p-3 focus-within:border-charm-cyan transition-colors">
            <span className="text-charm-cyan font-bold">{'>'}</span>
            <textarea
              ref={textAreaRef}
              value={input}
              onChange={handleInputChange}
              onKeyDown={handleKeyDown}
              placeholder="Digite !falar, !imaginar ou conversa natural..."
              className="w-full bg-transparent border-none text-charm-text placeholder-charm-subtext focus:ring-0 focus:outline-none resize-none h-6 py-0 font-mono leading-6"
              disabled={loading}
              rows={1}
              autoComplete="off"
            />
            <button
              onClick={handleSend}
              disabled={!input.trim() || loading}
              className="text-charm-subtext hover:text-charm-cyan disabled:opacity-30 transition-colors"
            >
              <Send className="w-4 h-4" />
            </button>
          </div>
          <p className="text-[10px] text-center text-charm-subtext mt-2 opacity-60">
            [!] Saída gerada por IA. Verifique as fontes. (Seta ↑ para histórico)
          </p>
        </div>
      </div>

      {/* Config Preview Panel */}
      <div className="hidden lg:flex w-72 flex-col gap-4">
        <div className="bg-charm-card border border-charm-border rounded p-4 flex-1 overflow-hidden">
            <h4 className="text-xs font-bold text-charm-subtext border-b border-charm-border pb-2 mb-3">CONFIG_ATUAL</h4>
            
            <div className="space-y-4">
            <div className="group">
                <label className="text-[10px] text-charm-purple block mb-1 group-hover:text-charm-pink transition-colors">SYSTEM_PROMPT</label>
                <div className="text-[10px] text-charm-subtext font-mono border-l border-charm-subtext pl-2 line-clamp-6 opacity-80">
                {config.systemPrompt}
                </div>
            </div>

            <div className="grid grid-cols-2 gap-2">
                <div>
                <label className="text-[10px] text-charm-purple block mb-1">TEMP</label>
                <div className="text-xs font-bold text-charm-text">{config.temperature}</div>
                </div>
                <div>
                <label className="text-[10px] text-charm-purple block mb-1">THINKING</label>
                <div className="text-xs font-bold text-charm-cyan">{config.thinkingLevel}</div>
                </div>
            </div>
            </div>
        </div>
        
        <div className="bg-charm-bg border border-charm-border border-dashed rounded p-3 text-center">
            <span className="text-2xl">🍬</span>
            <p className="text-[10px] text-charm-subtext mt-1">Charm Bracelet Vibes</p>
        </div>
      </div>
    </div>
  );
};

export default React.memo(Playground);